/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorscc;

import java.util.ArrayList;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author mig
 */
public class Interface extends javax.swing.JFrame {
    ArrayList<String> listaDados = new ArrayList<>();

    public Interface() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        initComponents();
        Simular.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                listaDados.add(tempo_simulacao.getText());
                listaDados.add(intervalo_clientes.getText());
                listaDados.add(tempo_servico_gasolina.getText());
                listaDados.add(tempo_servico_gasoleo.getText());
                listaDados.add(tempo_servico_loja.getText());
                listaDados.add(desvio_gasolina.getText());
                listaDados.add(desvio_gasoleo.getText());
                listaDados.add(desvio_loja.getText());
                listaDados.add(n_empregados_gasolina.getText());
                listaDados.add(n_empregados_gasoleo.getText());
                listaDados.add(n_empregados_loja.getText());
                
                try {
                    for(int i=0;i<listaDados.size();i++)
                        Double.parseDouble(listaDados.get(i));
                } catch (Exception exp) {
                    JOptionPane.showMessageDialog(null, "Parametros invalidos. Tente novamente.");
                }
                
                Simulador s = new Simulador(listaDados, 1);
                s.executa();
                
                String resultados = s.relat();
                JOptionPane.showMessageDialog(null, resultados, "Resultados Cenario 1", JOptionPane.PLAIN_MESSAGE);
            }
        });
        Simular2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                listaDados.add(tempo_simulacao2.getText());
                listaDados.add(intervalo_clientes2.getText());
                listaDados.add(tempo_servico_self.getText());
                listaDados.add(desvio_self.getText());
                listaDados.add(n_empregados_self.getText());
                
                try {
                    for(int i=0;i<listaDados.size();i++) 
                        Double.parseDouble(listaDados.get(i));
                } catch (Exception exp2) {
                    JOptionPane.showMessageDialog(null, "Parametros invalidos. Tente novamente.");
                }
                
                Simulador s = new Simulador(listaDados, 2);
                s.executa();
                
                String resultados = s.relat();
                JOptionPane.showMessageDialog(null, resultados, "Resultados Cenario 2", JOptionPane.PLAIN_MESSAGE);
            }
        });
    }
       
    protected void refresh() {
        this.revalidate();
    }
    
    public static void initInterface() {
        Interface I = new Interface();
        I.setResizable(false);
        I.setTitle("Simulador Bombas de Gasolina");
        //setContentPane(I);
        I.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        I.pack();
        I.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cenarios = new javax.swing.JTabbedPane();
        cenario1 = new javax.swing.JPanel();
        Panel_Cenarios = new javax.swing.JPanel();
        label_tempo_sim = new javax.swing.JLabel();
        label_chegada_clientes = new javax.swing.JLabel();
        tempo_simulacao = new javax.swing.JTextField();
        intervalo_clientes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Panel_Gasolina = new javax.swing.JPanel();
        titulo_gasolina = new javax.swing.JLabel();
        label_tempo_servico_gasolina = new javax.swing.JLabel();
        label_desvio_gasolina = new javax.swing.JLabel();
        label_empregados_gasolina = new javax.swing.JLabel();
        tempo_servico_gasolina = new javax.swing.JTextField();
        desvio_gasolina = new javax.swing.JTextField();
        n_empregados_gasolina = new javax.swing.JTextField();
        Panel_Loja = new javax.swing.JPanel();
        titulo_loja = new javax.swing.JLabel();
        label_tempo_servico_loja = new javax.swing.JLabel();
        label_desvio_loja = new javax.swing.JLabel();
        label_empregados_loja = new javax.swing.JLabel();
        tempo_servico_loja = new javax.swing.JTextField();
        desvio_loja = new javax.swing.JTextField();
        n_empregados_loja = new javax.swing.JTextField();
        Simular = new javax.swing.JButton();
        Panel_Gasoleo = new javax.swing.JPanel();
        titulo_gasoleo = new javax.swing.JLabel();
        label_tempo_servico_gasoleo = new javax.swing.JLabel();
        label_desvio_gasoleo = new javax.swing.JLabel();
        label_empregados_gasoleo = new javax.swing.JLabel();
        tempo_servico_gasoleo = new javax.swing.JTextField();
        desvio_gasoleo = new javax.swing.JTextField();
        n_empregados_gasoleo = new javax.swing.JTextField();
        cenario2 = new javax.swing.JPanel();
        Panel_Cenarios2 = new javax.swing.JPanel();
        label_tempo_sim2 = new javax.swing.JLabel();
        label_chegada_clientes2 = new javax.swing.JLabel();
        tempo_simulacao2 = new javax.swing.JTextField();
        intervalo_clientes2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Simular2 = new javax.swing.JButton();
        Panel_Gasoleo1 = new javax.swing.JPanel();
        titulo_self = new javax.swing.JLabel();
        label_tempo_self = new javax.swing.JLabel();
        label_desvio_self = new javax.swing.JLabel();
        label_empregados_self = new javax.swing.JLabel();
        tempo_servico_self = new javax.swing.JTextField();
        desvio_self = new javax.swing.JTextField();
        n_empregados_self = new javax.swing.JTextField();

        label_tempo_sim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tempo_sim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tempo_sim.setText("Tempo de Simulacao:");
        label_tempo_sim.setToolTipText("");

        label_chegada_clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_chegada_clientes.setText("Intervalo de chegada dos clientes:");

        tempo_simulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_simulacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CENARIO 1");

        javax.swing.GroupLayout Panel_CenariosLayout = new javax.swing.GroupLayout(Panel_Cenarios);
        Panel_Cenarios.setLayout(Panel_CenariosLayout);
        Panel_CenariosLayout.setHorizontalGroup(
            Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CenariosLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tempo_sim)
                    .addComponent(label_chegada_clientes))
                .addGap(18, 18, 18)
                .addGroup(Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tempo_simulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CenariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(387, 387, 387))
        );
        Panel_CenariosLayout.setVerticalGroup(
            Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CenariosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_sim)
                    .addComponent(tempo_simulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_CenariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_chegada_clientes)
                    .addComponent(intervalo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Gasolina.setPreferredSize(new java.awt.Dimension(250, 250));

        titulo_gasolina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo_gasolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_gasolina.setText("- GASOLINA -");

        label_tempo_servico_gasolina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_tempo_servico_gasolina.setText("Tempo Medio de Servico:");

        label_desvio_gasolina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_desvio_gasolina.setText("Desvio Padrao:");

        label_empregados_gasolina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_empregados_gasolina.setText("Nº Empregados:");

        javax.swing.GroupLayout Panel_GasolinaLayout = new javax.swing.GroupLayout(Panel_Gasolina);
        Panel_Gasolina.setLayout(Panel_GasolinaLayout);
        Panel_GasolinaLayout.setHorizontalGroup(
            Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GasolinaLayout.createSequentialGroup()
                .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_GasolinaLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(titulo_gasolina))
                    .addGroup(Panel_GasolinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_desvio_gasolina)
                            .addComponent(label_tempo_servico_gasolina)
                            .addComponent(label_empregados_gasolina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempo_servico_gasolina, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(desvio_gasolina)
                            .addComponent(n_empregados_gasolina))))
                .addContainerGap())
        );
        Panel_GasolinaLayout.setVerticalGroup(
            Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GasolinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_gasolina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_servico_gasolina)
                    .addComponent(tempo_servico_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_desvio_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desvio_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_GasolinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_empregados_gasolina)
                    .addComponent(n_empregados_gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Panel_Loja.setPreferredSize(new java.awt.Dimension(250, 250));

        titulo_loja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo_loja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_loja.setText("- LOJA -");

        label_tempo_servico_loja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_tempo_servico_loja.setText("Tempo Medio de Servico:");

        label_desvio_loja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_desvio_loja.setText("Desvio Padrao:");

        label_empregados_loja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_empregados_loja.setText("Nº Empregados:");

        javax.swing.GroupLayout Panel_LojaLayout = new javax.swing.GroupLayout(Panel_Loja);
        Panel_Loja.setLayout(Panel_LojaLayout);
        Panel_LojaLayout.setHorizontalGroup(
            Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LojaLayout.createSequentialGroup()
                .addGroup(Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_empregados_loja)
                    .addComponent(label_desvio_loja)
                    .addComponent(label_tempo_servico_loja))
                .addGap(10, 10, 10)
                .addGroup(Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempo_servico_loja, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(desvio_loja)
                    .addComponent(n_empregados_loja))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_loja)
                .addGap(101, 101, 101))
        );
        Panel_LojaLayout.setVerticalGroup(
            Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_loja)
                .addGap(11, 11, 11)
                .addGroup(Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_servico_loja)
                    .addComponent(tempo_servico_loja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_desvio_loja)
                    .addComponent(desvio_loja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Panel_LojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_empregados_loja)
                    .addComponent(n_empregados_loja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Simular.setText("SIMULAR");
        Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularActionPerformed(evt);
            }
        });

        Panel_Gasoleo.setPreferredSize(new java.awt.Dimension(250, 250));

        titulo_gasoleo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo_gasoleo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_gasoleo.setText("- GASOLEO -");

        label_tempo_servico_gasoleo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_tempo_servico_gasoleo.setText("Tempo Medio de Servico:");

        label_desvio_gasoleo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_desvio_gasoleo.setText("Desvio Padrao:");

        label_empregados_gasoleo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_empregados_gasoleo.setText("Nº Empregados:");

        javax.swing.GroupLayout Panel_GasoleoLayout = new javax.swing.GroupLayout(Panel_Gasoleo);
        Panel_Gasoleo.setLayout(Panel_GasoleoLayout);
        Panel_GasoleoLayout.setHorizontalGroup(
            Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GasoleoLayout.createSequentialGroup()
                .addGroup(Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_desvio_gasoleo)
                    .addComponent(label_tempo_servico_gasoleo)
                    .addComponent(label_empregados_gasoleo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempo_servico_gasoleo)
                    .addComponent(desvio_gasoleo)
                    .addComponent(n_empregados_gasoleo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_GasoleoLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(titulo_gasoleo)
                .addGap(91, 91, 91))
        );
        Panel_GasoleoLayout.setVerticalGroup(
            Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GasoleoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_gasoleo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_servico_gasoleo)
                    .addComponent(tempo_servico_gasoleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_desvio_gasoleo)
                    .addComponent(desvio_gasoleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_GasoleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_empregados_gasoleo)
                    .addComponent(n_empregados_gasoleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cenario1Layout = new javax.swing.GroupLayout(cenario1);
        cenario1.setLayout(cenario1Layout);
        cenario1Layout.setHorizontalGroup(
            cenario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cenario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Cenarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cenario1Layout.createSequentialGroup()
                        .addComponent(Panel_Gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Panel_Gasoleo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_Loja, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cenario1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(Simular, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cenario1Layout.setVerticalGroup(
            cenario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenario1Layout.createSequentialGroup()
                .addComponent(Panel_Cenarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cenario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel_Gasolina, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(Panel_Gasoleo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(Panel_Loja, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simular, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        Cenarios.addTab("Cenario 1", cenario1);

        label_tempo_sim2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tempo_sim2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tempo_sim2.setText("Tempo de Simulacao:");
        label_tempo_sim2.setToolTipText("");

        label_chegada_clientes2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_chegada_clientes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_chegada_clientes2.setText("Intervalo de chegada dos clientes:");

        tempo_simulacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_simulacao2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CENARIO 2");

        javax.swing.GroupLayout Panel_Cenarios2Layout = new javax.swing.GroupLayout(Panel_Cenarios2);
        Panel_Cenarios2.setLayout(Panel_Cenarios2Layout);
        Panel_Cenarios2Layout.setHorizontalGroup(
            Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Cenarios2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tempo_sim2)
                    .addComponent(label_chegada_clientes2))
                .addGap(18, 18, 18)
                .addGroup(Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intervalo_clientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempo_simulacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Cenarios2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(385, 385, 385))
        );
        Panel_Cenarios2Layout.setVerticalGroup(
            Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Cenarios2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_sim2)
                    .addComponent(tempo_simulacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Cenarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_chegada_clientes2)
                    .addComponent(intervalo_clientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Simular2.setText("SIMULAR");

        Panel_Gasoleo1.setPreferredSize(new java.awt.Dimension(250, 250));

        titulo_self.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo_self.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_self.setText("- SELF-SERVICE -");

        label_tempo_self.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_tempo_self.setText("Tempo Medio de Servico:");

        label_desvio_self.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_desvio_self.setText("Desvio Padrao:");

        label_empregados_self.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_empregados_self.setText("Nº Empregados:");

        javax.swing.GroupLayout Panel_Gasoleo1Layout = new javax.swing.GroupLayout(Panel_Gasoleo1);
        Panel_Gasoleo1.setLayout(Panel_Gasoleo1Layout);
        Panel_Gasoleo1Layout.setHorizontalGroup(
            Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Gasoleo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_desvio_self)
                    .addComponent(label_empregados_self)
                    .addComponent(label_tempo_self))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_empregados_self)
                    .addComponent(desvio_self)
                    .addComponent(tempo_servico_self))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Gasoleo1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(titulo_self)
                .addGap(83, 83, 83))
        );
        Panel_Gasoleo1Layout.setVerticalGroup(
            Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Gasoleo1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titulo_self)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempo_self)
                    .addComponent(tempo_servico_self, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_desvio_self)
                    .addComponent(desvio_self, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Gasoleo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_empregados_self)
                    .addComponent(n_empregados_self, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cenario2Layout = new javax.swing.GroupLayout(cenario2);
        cenario2.setLayout(cenario2Layout);
        cenario2Layout.setHorizontalGroup(
            cenario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenario2Layout.createSequentialGroup()
                .addGroup(cenario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cenario2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_Cenarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cenario2Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(Panel_Gasoleo1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cenario2Layout.createSequentialGroup()
                .addGap(0, 210, Short.MAX_VALUE)
                .addComponent(Simular2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        cenario2Layout.setVerticalGroup(
            cenario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenario2Layout.createSequentialGroup()
                .addComponent(Panel_Cenarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Gasoleo1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Simular2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        Cenarios.addTab("Cenario 2", cenario2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cenarios, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cenarios, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempo_simulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_simulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_simulacaoActionPerformed

    private void SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularActionPerformed
        
    }//GEN-LAST:event_SimularActionPerformed

    private void tempo_simulacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_simulacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_simulacao2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Cenarios;
    private javax.swing.JPanel Panel_Cenarios;
    private javax.swing.JPanel Panel_Cenarios2;
    private javax.swing.JPanel Panel_Gasoleo;
    private javax.swing.JPanel Panel_Gasoleo1;
    private javax.swing.JPanel Panel_Gasolina;
    private javax.swing.JPanel Panel_Loja;
    private javax.swing.JButton Simular;
    private javax.swing.JButton Simular2;
    private javax.swing.JPanel cenario1;
    private javax.swing.JPanel cenario2;
    private javax.swing.JTextField desvio_gasoleo;
    private javax.swing.JTextField desvio_gasolina;
    private javax.swing.JTextField desvio_loja;
    private javax.swing.JTextField desvio_self;
    private javax.swing.JTextField intervalo_clientes;
    private javax.swing.JTextField intervalo_clientes2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_chegada_clientes;
    private javax.swing.JLabel label_chegada_clientes2;
    private javax.swing.JLabel label_desvio_gasoleo;
    private javax.swing.JLabel label_desvio_gasolina;
    private javax.swing.JLabel label_desvio_loja;
    private javax.swing.JLabel label_desvio_self;
    private javax.swing.JLabel label_empregados_gasoleo;
    private javax.swing.JLabel label_empregados_gasolina;
    private javax.swing.JLabel label_empregados_loja;
    private javax.swing.JLabel label_empregados_self;
    private javax.swing.JLabel label_tempo_self;
    private javax.swing.JLabel label_tempo_servico_gasoleo;
    private javax.swing.JLabel label_tempo_servico_gasolina;
    private javax.swing.JLabel label_tempo_servico_loja;
    private javax.swing.JLabel label_tempo_sim;
    private javax.swing.JLabel label_tempo_sim2;
    private javax.swing.JTextField n_empregados_gasoleo;
    private javax.swing.JTextField n_empregados_gasolina;
    private javax.swing.JTextField n_empregados_loja;
    private javax.swing.JTextField n_empregados_self;
    private javax.swing.JTextField tempo_servico_gasoleo;
    private javax.swing.JTextField tempo_servico_gasolina;
    private javax.swing.JTextField tempo_servico_loja;
    private javax.swing.JTextField tempo_servico_self;
    private javax.swing.JTextField tempo_simulacao;
    private javax.swing.JTextField tempo_simulacao2;
    private javax.swing.JLabel titulo_gasoleo;
    private javax.swing.JLabel titulo_gasolina;
    private javax.swing.JLabel titulo_loja;
    private javax.swing.JLabel titulo_self;
    // End of variables declaration//GEN-END:variables
    
}
